### ISSUE TITLE
Schreibfehler im Modul 3 - Data Literacy

### ISSUE THREAD

**Issue by muddlebrain** [luebby/WWWEKI#1]
Im Modul 3 - Seite Data Literacy hat sich vermutlich ein Schreibfehler eingeschlichen:

_... behandeln wir die Frage: Was will ich **mich** mit Daten machen?_  => Das "mich" ist meiner Meinung nach zu viel ;)

**Comment by luebby** [comment]
Uups, vielen Dank!
